apiVersion: v1
kind: Service
metadata:
  name: servicediscussion-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: servicediscussion
  ports:
    - protocol: TCP
      port: 5034
      targetPort: 5034
      nodePort: 30134