apiVersion: apps/v1
kind: Deployment
metadata:
  name: diamadio-deployment
  namespace: pnud-agvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diamadio
  template:
    metadata:
      labels:
        app: diamadio
    spec:
      containers:
      - name: diamadio
        image: harbor.tsirylab.com/pnud-agvm/diamadio:${IMAGE_TAG}
        ports:
        - containerPort: 4001
        env:
        - name: VITE_API_URL
          valueFrom:
            secretKeyRef:
              name: agvm-gateway-secret
              key: VITE_API_URL
        - name: VITE_AUTH_TOKEN_KEY
          value: "${VITE_AUTH_TOKEN_KEY}"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 4001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: harbor-registry-secret