apiVersion: v1
kind: Secret
metadata:
  name: servicepublication-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASE: "${DB_DATABASE}"
  UPLOAD_URL: "${UPLOAD_URL}"