apiVersion: v1
kind: Secret
metadata:
  name: servicecitoyen-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  API_GATEWAY_URL: "${API_GATEWAY_URL}"
  FOKONTANY_SERVICE_URL: "${FOKONTANY_SERVICE_URL}"
  POSTGRES_DB: "${POSTGRES_DB}"