apiVersion: v1
kind: Service
metadata:
  name: servicecitoyen-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: servicecitoyen
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30011