apiVersion: v1
kind: Secret
metadata:
  name: servicepaiement-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_NAME: "${DB_NAME}"
  JWT_SECRET: "${JWT_SECRET}"
  JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
  AUTH_SERVICE_URL: "${AUTH_SERVICE_URL}"
  TERRITORY_SERVICE_URL: "${TERRITORY_SERVICE_URL}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  