{{- if and .Values.envFromSecret.enabled .Values.envFromSecret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice.secretName" . }}
  namespace: {{ include "microservice.namespace" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envFromSecret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
