pipeline {
    agent any

    environment {
        CONTAINER_NAME   = 'signal-incident-front'
        IMAGE_NAME       = 'signal-incident-front'
        IMAGE_TAG        = "${BUILD_NUMBER}"
        NEXT_PORT        = '3158'
        NEXT_PUBLIC_API_URL = 'https://api-incidence.itdcmada.com/api/v1'
        NEXT_PUBLIC_SOCKET_URL = 'https://api-incidence.itdcmada.com'
        NEXT_PUBLIC_SUPABASE_URL = credentials('INCIDENCE_SUPABASE_URL')
        NEXT_PUBLIC_SUPABASE_ANON_KEY = credentials('INCIDENCE_SUPABASE_ANON_KEY')
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = credentials('INCIDENCE_GOOGLE_MAPS_API_KEY') 
        NEXT_PUBLIC_GOOGLE_GEOLOCATION_API_KEY = credentials('INCIDENCE_GOOGLE_GEOLOCATION_API_KEY')
    }

    stages {
        stage('Build & Push') {
            steps {
                sh '''
                    docker build \
                        --build-arg NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} \
                        --build-arg NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL} \
                        --build-arg NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
                        --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY} \
                        --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY} \
                        --build-arg NEXT_PUBLIC_GOOGLE_GEOLOCATION_API_KEY=${NEXT_PUBLIC_GOOGLE_GEOLOCATION_API_KEY} \
                        --build-arg NEXT_PORT=${NEXT_PORT} \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }

        stage('Deploy the container') {
            steps {
                sh '''
                    # Vérifier si un conteneur avec le même nom existe
                    if [ "$(docker ps -aq -f name=${CONTAINER_NAME})" ]; then
                        echo "🛑 Un conteneur ${CONTAINER_NAME} existe déjà. Suppression..."
                        docker stop ${CONTAINER_NAME} || true
                        docker rm ${CONTAINER_NAME} || true
                    fi

                    echo "🚀 Démarrage du nouveau conteneur..."
                    docker run -d \
                        --name ${CONTAINER_NAME} \
                        -p ${NEXT_PORT}:${NEXT_PORT} \
                        --restart unless-stopped \
                        -e NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} \
                        -e NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL} \
                        -e NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
                        -e NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY} \
                        -e NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY} \
                        -e NEXT_PUBLIC_GOOGLE_GEOLOCATION_API_KEY=${NEXT_PUBLIC_GOOGLE_GEOLOCATION_API_KEY} \
                        -e NEXT_PORT=${NEXT_PORT} \
                        ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}