apiVersion: v1
kind: Secret
metadata:
  name: serviceaffiliation-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  USER_SERVICE_URL: "${USER_SERVICE_URL}"
  DB_DATABASE: "${DB_DATABASE}"
  DB_SYNCHRONIZE: "${DB_SYNCHRONIZE}"