apiVersion: v1
kind: Service
metadata:
  name: servicemonographies-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: servicemonographies
  ports:
    - protocol: TCP
      port: 5023
      targetPort: 5023
      nodePort: 30027