apiVersion: v1
kind: Service
metadata:
  name: serviceauth-service
  namespace: pnud-agvm
spec:
  selector:
    app: serviceauth
  ports:
    - protocol: TCP
      port: 5007
      targetPort: 5007
      nodePort: 30527
  type: NodePort