apiVersion: v1
kind: Secret
metadata:
  name: adminagvm-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  VITE_API_URL:${VITE_API_URL}
  VITE_PORT:${VITE_PORT}
  VITE_WS_URL:${VITE_WS_URL}
  VITE_CRIV_REGISTER_URL:${VITE_CRIV_REGISTER_URL}
  VITE_CRIV_REGISTER_USER_URL:${VITE_CRIV_REGISTER_USER_URL}