apiVersion: v1
kind: Service
metadata:
  name: servicemodernmarket-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: servicemodernmarket
  ports:
    - protocol: TCP
      port: 5033
      targetPort: 5033
      nodePort: 30133