pipeline {
    agent any

    environment {
        REGISTRY         = 'harbor.tsirylab.com'
        HARBOR_PROJECT   = 'pnud-agvm'
        IMAGE_NAME       = 'anjaranaka'
        IMAGE_TAG        = "${BUILD_NUMBER}"
        FULL_IMAGE_NAME  = "${REGISTRY}/${HARBOR_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}"
        NAMESPACE        = 'pnud-agvm'
        K8S_DIR          = 'k8s'
        DEPLOYMENT_NAME  = 'anjaranaka'
        SERVICE_NAME     = 'anjaranaka-service'
        HPA_NAME         = 'anjaranaka-hpa'
        SECRET_NAME      = 'anjaranaka-secret'
        VITE_PORT        = '4005'
        VITE_API_URL_SERVICECITOYEN = 'https://gateway.tsirylab.com/servicecitoyen'
        VITE_API_URL_SERVICEAUTH = 'https://auth.tsirylab.com/serviceauth'
        VITE_API_URL_SERVICEZONE = 'https://zone.tsirylab.com/servicezone'
        VITE_API_URL_SERVICEOFFRECOMMUNE = 'https://offrecommune.tsirylab.com/serviceoffrecommune'
        VITE_API_SERVICEMODERNEMARKET = 'https://modernemarket.tsirylab.com/servicemodernemarket'
    }

    stages {
        stage('Build & Push') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'harbor-credentials',
                                     usernameVariable: 'HARBOR_USER',
                                     passwordVariable: 'HARBOR_PASS')
                ]) {
                    sh '''
                        set -e
                        docker logout ${REGISTRY} || true

                        docker build \
                          --build-arg VITE_API_URL_SERVICECITOYEN=${VITE_API_URL_SERVICECITOYEN} \
                          --build-arg VITE_API_URL_SERVICEAUTH=${VITE_API_URL_SERVICEAUTH} \
                          --build-arg VITE_API_URL_SERVICEZONE=${VITE_API_URL_SERVICEZONE} \
                          --build-arg VITE_API_URL_SERVICEOFFRECOMMUNE=${VITE_API_URL_SERVICEOFFRECOMMUNE} \
                          --build-arg VITE_API_SERVICEMODERNEMARKET=${VITE_API_SERVICEMODERNEMARKET} \
                          --build-arg VITE_PORT=${VITE_PORT} \
                          -t ${FULL_IMAGE_NAME} .

                        echo ${HARBOR_PASS} | \
                          docker login -u ${HARBOR_USER} --password-stdin ${REGISTRY}

                        docker push ${FULL_IMAGE_NAME}
                        docker logout ${REGISTRY}
                    '''
                }
            }
        }

        stage('Deploy to K3s') {
            steps {
                withCredentials([
                    file(credentialsId: 'kubeconfig-jenkins', variable: 'KUBECONFIG'),
                    usernamePassword(credentialsId: 'harbor-credentials',
                                     usernameVariable: 'HARBOR_USER',
                                     passwordVariable: 'HARBOR_PASS')
                ]) {
                    sh '''
                        set -e
                        export KUBECONFIG=${KUBECONFIG}

                        kubectl create namespace ${NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -

                        kubectl delete secret harbor-registry-secret -n ${NAMESPACE} --ignore-not-found
                        kubectl create secret docker-registry harbor-registry-secret \
                          --docker-server=${REGISTRY} \
                          --docker-username="${HARBOR_USER}" \
                          --docker-password="${HARBOR_PASS}" \
                          --namespace=${NAMESPACE}

                        kubectl delete secret ${SECRET_NAME} -n ${NAMESPACE} --ignore-not-found
                        kubectl create secret generic ${SECRET_NAME} \
                          --from-literal=VITE_API_URL_SERVICECITOYEN="${VITE_API_URL_SERVICECITOYEN}" \
                          --from-literal=VITE_API_URL_SERVICEAUTH="${VITE_API_URL_SERVICEAUTH}" \
                          --from-literal=VITE_API_URL_SERVICEZONE="${VITE_API_URL_SERVICEZONE}" \
                          --from-literal=VITE_API_URL_SERVICEOFFRECOMMUNE="${VITE_API_URL_SERVICEOFFRECOMMUNE}" \
                          --from-literal=VITE_API_SERVICEMODERNEMARKET="${VITE_API_SERVICEMODERNEMARKET}" \
                          --from-literal=VITE_PORT="${VITE_PORT}" \
                          --namespace=${NAMESPACE}

                        # template toutes les ressources
                        for res in deployment service hpa secret; do
                            envsubst < ${K8S_DIR}/${DEPLOYMENT_NAME}.$res.yaml > /tmp/${DEPLOYMENT_NAME}.$res.yaml
                            kubectl apply -f /tmp/${DEPLOYMENT_NAME}.$res.yaml
                        done

                        kubectl rollout status deployment/${DEPLOYMENT_NAME} -n ${NAMESPACE} --timeout=600s
                        kubectl get pods -n ${NAMESPACE} -l app=${DEPLOYMENT_NAME}
                    '''
                }
            }
        }
    }

    post { always { cleanWs() } }
}