apiVersion: v1
kind: Secret
metadata:
  name: assistance-juridique-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  VITE_API_URL: "${VITE_API_URL}"
  VITE_AUTH_TOKEN_KEY: "${VITE_AUTH_TOKEN_KEY}"
  VITE_DISABLE_AUTH: "${VITE_DISABLE_AUTH}"
  VITE_APP_NAME: "${VITE_APP_NAME}"
  VITE_PORT: "${VITE_PORT}"