pipeline {
    agent any

    environment {
        CONTAINER_NAME   = 'material-front'
        IMAGE_NAME       = 'material-front'
        IMAGE_TAG        = "${BUILD_NUMBER}"
        PORT        = '4001'
        VITE_API_URL     = 'https://material-api.chu-andrainjato.mg'
        VITE_CLERK_PUBLISHABLE_KEY = credentials('VITE_CLERK_PUBLISHABLE_KEY_ID')
        NGROK_AUTHTOKEN = credentials('NGROK_AUTHTOKEN_ID')
        VITE_ENCRYPT_KEY = credentials('VITE_ENCRYPT_KEY_ID')
    }

    stages {
        stage('Build & Push') {
            steps {
                sh '''
                    echo "🛠️ Build de l'image Docker..."
                    docker build \
                      --build-arg VITE_API_URL=${VITE_API_URL} \
                      --build-arg VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY} \
                      --build-arg NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} \
                      --build-arg VITE_ENCRYPT_KEY=${VITE_ENCRYPT_KEY} \
                      --build-arg PORT=${PORT} \
                      -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }

        stage('Deploy the container') {
            steps {
                sh '''
                    echo "🧹 Suppression du conteneur existant s'il existe..."
                    docker rm -f ${CONTAINER_NAME} || true

                    echo "🚀 Démarrage du nouveau conteneur..."
                    docker run -d \
                        --name ${CONTAINER_NAME} \
                        -p ${PORT}:${PORT} \
                        --restart unless-stopped \
                        -e VITE_API_URL=${VITE_API_URL} \
                        -e VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY} \
                        -e NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} \
                        -e VITE_ENCRYPT_KEY=${VITE_ENCRYPT_KEY} \
                        -e PORT=${PORT} \
                        ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}