#!/bin/sh

# Exporter les variables pour qu'elles soient prises en compte
export NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
export NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
export NEXT_PUBLIC_APP_DESCRIPTION=${NEXT_PUBLIC_APP_DESCRIPTION}
export NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
export NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
export NEXT_PUBLIC_ACCESS_TOKEN_EXPIRE_MINUTES=${NEXT_PUBLIC_ACCESS_TOKEN_EXPIRE_MINUTES}


echo "✅ Environnement chargé avec les valeurs suivantes :"
echo "NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}"
echo "NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}"
echo "NEXT_PUBLIC_APP_DESCRIPTION=${NEXT_PUBLIC_APP_DESCRIPTION}"
echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}"
echo "NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}"
echo "NEXT_PUBLIC_ACCESS_TOKEN_EXPIRE_MINUTES=${NEXT_PUBLIC_ACCESS_TOKEN_EXPIRE_MINUTES}"

# Lancer Next.js
npx next start -p 3147