pipeline {
    agent any

    environment {
        IMAGE_NAME = 'billet-mahaleo-backend'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        CONTAINER_NAME = 'billet-mahaleo-backend-container'
        DB_USER = credentials('DB_USER_ID')
        DB_PASSWORD = credentials('DB_PASSWORD_ID')
        DB_HOST = credentials('DB_HOST_ID')
        DB_NAME = 'billet_mahaleo'
        DB_PORT = credentials('DB_PORT_ID')
        PORT = '3136'
    }

    stages {

        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building the Docker image with environment variables...'
                    sh """
                    docker build \
                        --build-arg DB_USER=${DB_USER} \
                        --build-arg DB_PASSWORD=${DB_PASSWORD} \
                        --build-arg DB_HOST=${DB_HOST} \
                        --build-arg DB_NAME=${DB_NAME} \
                        --build-arg DB_PORT=${DB_PORT} \
                        --build-arg PORT=${PORT} \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    """
                }
            }
        }


        stage('Deploy Containers') {
            steps {
                script {
                    echo 'Checking if the container is already running...'
                    sh """
                    if [ "\$(docker ps -q -f name=${CONTAINER_NAME})" ]; then
                        echo "Stopping and removing existing container..."
                        docker stop ${CONTAINER_NAME}
                        docker rm ${CONTAINER_NAME}
                    fi
                    """

                    echo 'Running the Docker container with environment variables...'
                    sh """
                    docker run -d --name ${CONTAINER_NAME} \
                        -e DB_USER=${DB_USER} \
                        -e DB_PASSWORD=${DB_PASSWORD} \
                        -e DB_HOST=${DB_HOST} \
                        -e DB_NAME=${DB_NAME} \
                        -e DB_PORT=${DB_PORT} \
                        -e PORT=${PORT} \
                        -p ${PORT}:${PORT} \
                        ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }
    }

    post {
        always {
            script {
                echo 'Cleaning workspace...'
                cleanWs()
            }
        }
    }
}
