apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilite-urbaine-client-deployment
  namespace: pnud-agvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilite-urbaine-client
  template:
    metadata:
      labels:
        app: mobilite-urbaine-client
    spec:
      containers:
      - name: mobilite-urbaine-client
        image: harbor.tsirylab.com/pnud-agvm/mobilite-urbaine-client:${IMAGE_TAG}
        ports:
        - containerPort: 4007
        env:
        - name: VITE_API_BASE_URL
          valueFrom:
            secretKeyRef:
              name: agvm-gateway-secret
              key: VITE_API_BASE_URL
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 4007
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4007
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: harbor-registry-secret