apiVersion: v1
kind: Service
metadata:
  name: mobilite-urbaine-service
  namespace: pnud-agvm
spec:
  selector:
    app: mobilite-urbaine-client
  ports:
    - protocol: TCP
      port: 4007
      targetPort: 4007
      nodePort: 30044
  type: NodePort