apiVersion: v1
kind: Service
metadata:
  name: serviceregis-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: serviceregis
  ports:
    - protocol: TCP
      port: 5027
      targetPort: 5027
      nodePort: 30037