apiVersion: v1
kind: Secret
metadata:
  name: serviceentreprise-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"