apiVersion: apps/v1
kind: Deployment
metadata:
  name: anjaranaka
  namespace: pnud-agvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anjaranaka
  template:
    metadata:
      labels:
        app: anjaranaka
    spec:
      containers:
      - name: anjaranaka
        image: ${FULL_IMAGE_NAME}
        imagePullPolicy: Always
        ports:
          - containerPort: 4005
            name: http
        envFrom:
          - secretRef:
              name: anjaranaka-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: harbor-registry-secret