apiVersion: v1
kind: Service
metadata:
  name: servicetheme-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: servicetheme
  ports:
    - protocol: TCP
      port: 5017
      targetPort: 5017
      nodePort: 30028