apiVersion: v1
kind: Secret
metadata:
  name: servicenotification-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASE: "${DB_DATABASE}"
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  GOOGLE_REDIRECT_URI: "${GOOGLE_REDIRECT_URI}"
  GOOGLE_REFRESH_TOKEN: "${GOOGLE_REFRESH_TOKEN}"
  EMAIL_FROM: "${EMAIL_FROM}"