apiVersion: apps/v1
kind: Deployment
metadata:
  name: agvm-client-deployment
  namespace: pnud-agvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agvm-client
  template:
    metadata:
      labels:
        app: agvm-client
    spec:
      containers:
      - name: agvm-client
        image: ${FULL_IMAGE_NAME}
        imagePullPolicy: Always
        ports:
          - containerPort: 4004
            name: http
        envFrom:
          - secretRef:
              name: criv-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: harbor-registry-secret