apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agvm-client-hpa
  namespace: pnud-agvm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agvm-client-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80