apiVersion: apps/v1
kind: Deployment
metadata:
  name: agvm-client-deployment
  namespace: pnud-agvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agvm-client
  template:
    metadata:
      labels:
        app: agvm-client
    spec:
      containers:
      - name: agvm-client
        image: harbor.tsirylab.com/pnud-agvm/agvm-client:latest
        ports:
        - containerPort: 4004
        env:
        - name: VITE_API_URL
          valueFrom:
            secretKeyRef:
              name: agvm-gateway-secret
              key: VITE_API_URL
        - name: VITE_API_TIMEOUT
          value: "100000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 4004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4004
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: harbor-registry-secret