apiVersion: apps/v1
kind: Deployment
metadata:
  name: diamadio-admin-deployment
  namespace: pnud-agvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diamadio-admin
  template:
    metadata:
      labels:
        app: diamadio-admin
    spec:
      containers:
      - name: diamadio-admin
        image: harbor.tsirylab.com/pnud-agvm/diamadio-admin:latest
        ports:
        - containerPort: 4002
        env:
        - name: REACT_APP_API_BASE_URL
          valueFrom:
            secretKeyRef:
              name: agvm-gateway-secret
              key: REACT_APP_API_BASE_URL
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 4002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4002
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: harbor-registry-secret