apiVersion: v1
kind: Service
metadata:
  name: diamadio-admin-service
  namespace: pnud-agvm
spec:
  selector:
    app: diamadio-admin
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
      nodePort: 30043
  type: NodePort