apiVersion: v1
kind: Secret
metadata:
  name: itantsoroka-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  VITE_APP_BASE_URL: "${VITE_AUTH_BASE_URL}"
  VITE_AUTH_BASE_URL: "${VITE_AUTH_BASE_URL}"