pipeline {
    agent any

    environment {
        REGISTRY = "harbor.tsirylab.com"
        HARBOR_PROJECT = "pnud-agvm"
        IMAGE_NAME = "diamadio"
        IMAGE_TAG = "latest"
        FULL_IMAGE_NAME = "${REGISTRY}/${HARBOR_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}"
        DEPLOYMENT_NAME = "diamadio-deployment"
        NAMESPACE = "pnud-agvm"
        VITE_AUTH_TOKEN_KEY = '100000'
        VITE_PORT = "4004"
        NODE_PORT = "30042"
        K8S_DIR = "k8s"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building the Docker image...'
                    sh """
                        docker build \\
                            --build-arg VITE_AUTH_TOKEN_KEY=${VITE_AUTH_TOKEN_KEY} \\
                            --build-arg VITE_PORT=${VITE_PORT} \\
                            -t ${IMAGE_NAME}:${IMAGE_TAG} .
                        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${FULL_IMAGE_NAME}
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'harbor-credentials', usernameVariable: 'HARBOR_USER', passwordVariable: 'HARBOR_PASS')]) {
                    script {
                        echo 'Logging in to Harbor...'
                        sh """
                            echo "${HARBOR_PASS}" | docker login -u "${HARBOR_USER}" --password-stdin ${REGISTRY}
                            docker push ${FULL_IMAGE_NAME}
                            docker logout ${REGISTRY}
                        """
                    }
                }
            }
        }

        stage('Deploy to K3s') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-jenkins', variable: 'KUBECONFIG')],
                                [string(credentialsId: 'GATEWAY_URL_ID', variable: 'VITE_API_URL')]) {
                    script {
                        echo 'Injecting secret for VITE_API_URL...'
                        sh """
                            export KUBECONFIG=${KUBECONFIG}
                            kubectl create namespace ${NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -
                            kubectl delete secret agvm-gateway-secret -n ${NAMESPACE} --ignore-not-found
                            kubectl create secret generic agvm-gateway-secret -n ${NAMESPACE} --from-literal=VITE_API_URL="${VITE_API_URL}"
                        """
                        echo 'Deploying to K3s cluster...'
                        sh """
                            export KUBECONFIG=${KUBECONFIG}
                            kubectl apply -f ${K8S_DIR}/deployment.yaml
                            kubectl apply -f ${K8S_DIR}/service.yaml
                            kubectl apply -f ${K8S_DIR}/hpa.yaml
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                echo 'Cleaning workspace...'
                cleanWs()
            }
        }
    }
}