apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceconstruction
  namespace: ${NAMESPACE}
  labels:
    app: serviceconstruction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceconstruction
  template:
    metadata:
      labels:
        app: serviceconstruction
    spec:
      containers:
        - name: serviceconstruction
          image: ${FULL_IMAGE_NAME}
          imagePullPolicy: Always
          ports:
            - containerPort: 5041
              name: http
          envFrom:
            - secretRef:
                name: serviceconstruction-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /serviceconstruction
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /serviceconstruction
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      imagePullSecrets:
        - name: harbor-registry-secret