pipeline {
    agent any

    environment {
        IMAGE_NAME = 'urbanisme-image'
        IMAGE_TAG = 'latest'
        CONTAINER_NAME = 'urbanisme-container'

        PORT = '4008'
        VITE_APP_SERVICENOTIFICATION = 'https://gateway.tsirylab.com/servicenotification'
        VITE_APP_SERVICEAUTH = 'https://gateway.tsirylab.com/serviceauth'
        VITE_APP_REGISTER_URL = 'https://criv.tsirylab.com'
    }

    stages {

        stage('Build Docker Image') {
            steps {
                script {
                    echo 'Building the Docker image with environment variables...'
                    sh """
                    docker build \
                        --build-arg PORT=${PORT} \
                        --build-arg VITE_APP_SERVICENOTIFICATION=${VITE_APP_SERVICENOTIFICATION} \
                        --build-arg VITE_APP_SERVICEAUTH=${VITE_APP_SERVICEAUTH} \
                        --build-arg VITE_APP_REGISTER_URL=${VITE_APP_REGISTER_URL} \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    """
                }
            }
        }

        stage('Deploy Containers') {
            steps {
                script {
                    echo 'Checking if the container is already running...'
                    sh '''
                    if [ "$(docker ps -q -f name=${CONTAINER_NAME})" ]; then
                        echo "Stopping and removing existing container..."
                        docker stop ${CONTAINER_NAME}
                        docker rm ${CONTAINER_NAME}
                    fi
                    '''

                    echo 'Running the Docker container with environment variables...'
                    sh '''
                    docker run -d --name ${CONTAINER_NAME} \
                        -p ${PORT}:${PORT} \
                        -e PORT=${PORT} \
                        -e VITE_APP_SERVICENOTIFICATION=${VITE_APP_SERVICENOTIFICATION} \
                        -e VITE_APP_SERVICEAUTH=${VITE_APP_SERVICEAUTH} \
                        -e VITE_APP_REGISTER_URL=${VITE_APP_REGISTER_URL} \
                        ${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }
    }

    post {
        always {
            script {
                echo 'Cleaning workspace...'
                cleanWs()
            }
        }
    }
}
