apiVersion: v1
kind: Service
metadata:
  name: serviceproject-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: serviceproject
  ports:
    - protocol: TCP
      port: 5019
      targetPort: 5019
      nodePort: 30026