version: "3.9"

services:
  backend-gesco:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gesco-backend
    ports:
      - "3141:3141"
    volumes:
      - uploads:/app/uploads
    env_file:
      - .env
    networks:
      - gesco-network

volumes:
  uploads:

networks:
  gesco-network:
    driver: bridge
