apiVersion: v1
kind: Service
metadata:
  name: apigateway-dev-service
  namespace: pnud-agvm
spec:
  type: NodePort
  selector:
    app: apigateway-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5010
      nodePort: 32081