apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicemission
  namespace: ${NAMESPACE}
  labels:
    app: servicemission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicemission
  template:
    metadata:
      labels:
        app: servicemission
    spec:
      containers:
        - name: servicemission
          image: ${FULL_IMAGE_NAME}
          imagePullPolicy: Always
          ports:
            - containerPort: 5022
              name: http
          envFrom:
            - secretRef:
                name: servicemission-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /servicemission
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /servicemission
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      imagePullSecrets:
        - name: harbor-registry-secret