version: "3.9"

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rsu-backend
    ports:
      - "3138:3138"
    volumes:
      - uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - rsu-network

  redis:
    image: redis:7-alpine
    container_name: rsu-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rsu-network
    volumes:
      - redis-data:/data

volumes:
  uploads:
  redis-data:

networks:
  rsu-network:
    driver: bridge
