pipeline {
    agent any
    environment {
        CONTAINER_NAME   = 'rsu-backend'
        IMAGE_NAME       = 'rsu-backend'
        IMAGE_TAG        = "${BUILD_NUMBER}"
        // Variables non sensibles
        POSTGRES_USER    = credentials('DB_USER_ID')
        POSTGRES_DB      = 'rsu'
        POSTGRES_HOST    = credentials('DB_HOST_ID')
        POSTGRES_PORT    = credentials('DB_PORT_ID')
        REDIS_HOST       = credentials('REDIS_HOST_ID')
        REDIS_PORT       = credentials('REDIS_PORT_ID')
        REDIS_DB         = '0'
        MAIL_USERNAME    = credentials('SMTP_USER_ID')
        MAIL_FROM        = credentials('SMTP_USER_ID')
        MAIL_PORT        = '587'
        MAIL_SERVER      = credentials('SMTP_HOST_ID')
        // Variables sensibles via credentials Jenkins
        POSTGRES_PASSWORD = credentials('DB_PASSWORD_ID')
        MAIL_PASSWORD    = credentials('MAIL_PASSWORD_ID')
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker-compose build'
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    docker-compose up -d \
                    -e POSTGRES_USER=${POSTGRES_USER} \
                    -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
                    -e POSTGRES_DB=${POSTGRES_DB} \
                    -e POSTGRES_HOST=${POSTGRES_HOST} \
                    -e POSTGRES_PORT=${POSTGRES_PORT} \
                    -e REDIS_HOST=${REDIS_HOST} \
                    -e REDIS_PORT=${REDIS_PORT} \
                    -e REDIS_DB=${REDIS_DB} \
                    -e MAIL_USERNAME=${MAIL_USERNAME} \
                    -e MAIL_PASSWORD=${MAIL_PASSWORD} \
                    -e MAIL_FROM=${MAIL_FROM} \
                    -e MAIL_PORT=${MAIL_PORT} \
                    -e MAIL_SERVER=${MAIL_SERVER}
                '''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}