apiVersion: v1
kind: Secret
metadata:
  name: servicealignement-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DATABASE_HOST: "${DATABASE_HOST}"
  DATABASE_PORT: "${DATABASE_PORT}"
  DATABASE_USERNAME: "${DATABASE_USERNAME}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  DATABASE_NAME: "${DATABASE_NAME}"