apiVersion: v1
kind: Secret
metadata:
  name: serviceupload-secret
  namespace: pnud-agvm
type: Opaque
stringData:
  MINIO_END_POINT: "<ta_valeur_minio_endpoint>"
  MINIO_PORT: "<ta_valeur_minio_port>"
  MINIO_ACCESS_KEY: "<ta_valeur_minio_access_key>"
  MINIO_SECRET_KEY: "<ta_valeur_minio_secret_key>"